In [1]:
#Import all needed Packages

import matplotlib.pyplot as plt

import pandas as pd

import numpy as np

In [2]:
#Set path to .csv file original Data Frame iss IMDB_df
IMDB_df = pd.read_csv('IMDB_Horror_Movies.csv')
IMDB_df.head()

,Title,Genres,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Plot,Cast,Language,Filming Locations,Budget
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,NaN,3.9,91 min,"Directed by Elias. With Jason Vail, Nicholas W...",Jason Vail|Nicholas Wilder|Sarah Schoofs|Kirst...,English,"New York, USA",NaN
1,The Haunting of Mia Moss (2017),Horror,13-Jan-17,USA,NaN,NaN,NaN,"Directed by Jake Zelch. With Nicola Fiore, Bri...",Nicola Fiore|Brinke Stevens|Curtis Carnahan|Ja...,English,NaN,"$30,000"
2,Sleepwalking (2017),Horror,21-Oct-17,Canada,NaN,NaN,NaN,"Directed by David Briggs. With Alysia Topol, A...",Alysia Topol|Anthony Makela|Kelsi Ashley|Patri...,English,"Sudbury, Ontario, Canada",NaN
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,NOT RATED,3.7,82 min,"Directed by M. Kelley, Shawn C. Phillips, Alex...",Veronica Ricci|Nicholas Adam Clark|James Culle...,English,"Baltimore, Maryland, USA",NaN
4,Infidus (2015),Crime| Drama| Horror,10-Apr-15,USA,NaN,5.8,80 min,"Directed by Giulio De Santi. With Bonini Mino,...",Bonini Mino|Massimo Caratelli|Maurizio Zaffino...,Italian,NaN,NaN

In [3]:
#Clean .csv file
IMDB_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328 entries, 0 to 3327
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              3328 non-null   object
 1   Genres             3327 non-null   object
 2   Release Date       3328 non-null   object
 3   Release Country    3328 non-null   object
 4   Movie Rating       1451 non-null   object
 5   Review Rating      3076 non-null   float64
 6   Movie Run Time     2784 non-null   object
 7   Plot               3327 non-null   object
 8   Cast               3314 non-null   object
 9   Language           3256 non-null   object
 10  Filming Locations  2096 non-null   object
 11  Budget             1234 non-null   object
dtypes: float64(1), object(11)
memory usage: 312.1+ KB

In [4]:
## .describe() to look at row counts
IMDB_df.describe()

       Review Rating
count    3076.000000
mean        5.077016
std         1.474272
min         1.000000
25%         4.000000
50%         5.000000
75%         6.100000
max         9.800000

In [5]:
# Dropped "Movie Rating", "Movie Run Time", "Plot", "Cast", "Language", and "Budget" columns to keep relevant data
#First iteration "Best used for x"
IMDB_Clean1_df = IMDB_df[["Title", "Genres", "Release Date","Release Country" ,"Review Rating", "Filming Locations"]]
IMDB_Clean1_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA"
1,The Haunting of Mia Moss (2017),Horror,13-Jan-17,USA,NaN,NaN
2,Sleepwalking (2017),Horror,21-Oct-17,Canada,NaN,"Sudbury, Ontario, Canada"
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA"
4,Infidus (2015),Crime| Drama| Horror,10-Apr-15,USA,5.8,NaN

In [6]:
# .info to see non-Null Counts
IMDB_Clean1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328 entries, 0 to 3327
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              3328 non-null   object
 1   Genres             3327 non-null   object
 2   Release Date       3328 non-null   object
 3   Release Country    3328 non-null   object
 4   Review Rating      3076 non-null   float64
 5   Filming Locations  2096 non-null   object
dtypes: float64(1), object(5)
memory usage: 156.1+ KB

In [7]:
# Dropped nulls .info again to check row len
IMDB_Clean2_df = IMDB_Clean1_df.dropna()
IMDB_Clean2_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 3327
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              1960 non-null   object
 1   Genres             1960 non-null   object
 2   Release Date       1960 non-null   object
 3   Release Country    1960 non-null   object
 4   Review Rating      1960 non-null   float64
 5   Filming Locations  1960 non-null   object
dtypes: float64(1), object(5)
memory usage: 107.2+ KB

In [8]:
# .value count for genre column 
IMDB_Clean2_df.Genres.value_counts()

Genres
 Horror                                                 482
 Horror| Thriller                                       304
 Comedy| Horror                                         143
 Horror| Mystery| Thriller                              131
 Drama| Horror| Thriller                                104
                                                       ...
 Drama| Horror| Musical| Thriller                         1
 Action| Crime| Horror| Western                           1
 Action| Adult| Comedy| Horror| Sci-Fi| Western           1
 Comedy| Horror| Romance| Thriller                        1
 Comedy| Fantasy| Horror| Mystery| Romance| Thriller      1
Name: count, Length: 196, dtype: int64

In [9]:
# iterate through genre columns to count max number of total genres listed 
var = [len(x.split('|'))for x in IMDB_Clean2_df['Genres'].tolist()]
var.sort()
var[-10:]

[6, 6, 6, 6, 7, 7, 7, 7, 7, 8]

In [10]:
# View Release Date column for quick check of variations in data entry
IMDB_Clean2_df["Release Date"].head(25)

0     26-Oct-12
3     23-Apr-13
7     25-Apr-15
8     28-May-17
11     1-May-12
13         2013
14    21-Mar-17
15    13-Jan-17
16    23-Mar-15
17     8-Apr-16
19    16-Sep-14
20    18-Feb-12
21     8-Jun-13
22     5-May-15
24    25-May-16
25     1-Oct-12
26         2012
28    15-Aug-14
29         2013
30    19-Apr-13
31     2-Nov-16
36     9-Mar-17
38    21-Feb-14
39    27-Sep-14
40    31-Mar-14
Name: Release Date, dtype: object

In [11]:
### Create genre columns 1-8
for x in range(1,9):
    IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
IMDB_Clean2_df.head()

C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_16660\3497392165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#
IMDB_Clean3_df = IMDB_Clean2_df.reset_index(drop=True)
IMDB_Clean3_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#
for x,y in enumerate(IMDB_Clean3_df['Genres'].tolist()):
    try:
        temp_var = y.split('|')
        for i,j in enumerate(temp_var):

            IMDB_Clean3_df.at[x,f"Genre_{i+1}"]=j

    except:
        continue
IMDB_Clean3_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Drama,Horror,Thriller,NaN,NaN,NaN,NaN,NaN
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Comedy,Horror,Thriller,NaN,NaN,NaN,NaN,NaN
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Action,Drama,Horror,Sci-Fi,NaN,NaN,NaN,NaN
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",Horror,Mystery,Thriller,NaN,NaN,NaN,NaN,NaN
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",Adventure,Comedy,Horror,NaN,NaN,NaN,NaN,NaN

In [14]:
#
IMDB_Clean3_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Drama,Horror,Thriller,NaN,NaN,NaN,NaN,NaN
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Comedy,Horror,Thriller,NaN,NaN,NaN,NaN,NaN
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Action,Drama,Horror,Sci-Fi,NaN,NaN,NaN,NaN
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",Horror,Mystery,Thriller,NaN,NaN,NaN,NaN,NaN
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",Adventure,Comedy,Horror,NaN,NaN,NaN,NaN,NaN

In [15]:
#
IMDB_Clean3_df[['Day', 'Month', 'Year']] =  IMDB_Clean3_df['Release Date'].str.split("-", expand = True)
print(IMDB_Clean3_df.count())
IMDB_Clean3_df.head()

Title                1960
Genres               1960
Release Date         1960
Release Country      1960
Review Rating        1960
Filming Locations    1960
Genre_1              1960
Genre_2              1478
Genre_3               859
Genre_4               310
Genre_5                90
Genre_6                25
Genre_7                 6
Genre_8                 1
Day                  1960
Month                1865
Year                 1865
dtype: int64

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8,Day,Month,Year
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Drama,Horror,Thriller,NaN,NaN,NaN,NaN,NaN,26,Oct,12
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Comedy,Horror,Thriller,NaN,NaN,NaN,NaN,NaN,23,Apr,13
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Action,Drama,Horror,Sci-Fi,NaN,NaN,NaN,NaN,25,Apr,15
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",Horror,Mystery,Thriller,NaN,NaN,NaN,NaN,NaN,28,May,17
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",Adventure,Comedy,Horror,NaN,NaN,NaN,NaN,NaN,1,May,12

In [16]:
#
IMDB_Clean3_df['Release Year'] = pd.DatetimeIndex(IMDB_Clean3_df['Release Date']).year
IMDB_Clean3_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8,Day,Month,Year,Release Year
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Drama,Horror,Thriller,NaN,NaN,NaN,NaN,NaN,26,Oct,12,2012
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Comedy,Horror,Thriller,NaN,NaN,NaN,NaN,NaN,23,Apr,13,2013
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Action,Drama,Horror,Sci-Fi,NaN,NaN,NaN,NaN,25,Apr,15,2015
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",Horror,Mystery,Thriller,NaN,NaN,NaN,NaN,NaN,28,May,17,2017
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",Adventure,Comedy,Horror,NaN,NaN,NaN,NaN,NaN,1,May,12,2012

In [17]:
#
IMDB_Clean3_df.count()

Title                1960
Genres               1960
Release Date         1960
Release Country      1960
Review Rating        1960
Filming Locations    1960
Genre_1              1960
Genre_2              1478
Genre_3               859
Genre_4               310
Genre_5                90
Genre_6                25
Genre_7                 6
Genre_8                 1
Day                  1960
Month                1865
Year                 1865
Release Year         1960
dtype: int64

In [18]:
#
IMDB_Clean4_df = IMDB_Clean3_df.drop(columns = ["Release Date","Day", "Year"])
IMDB_Clean4_df.head()

,Title,Genres,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8,Month,Release Year
0,Gut (2012),Drama| Horror| Thriller,USA,3.9,"New York, USA",Drama,Horror,Thriller,NaN,NaN,NaN,NaN,NaN,Oct,2012
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,USA,3.7,"Baltimore, Maryland, USA",Comedy,Horror,Thriller,NaN,NaN,NaN,NaN,NaN,Apr,2013
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,Japan,6.5,"Tokyo, Japan",Action,Drama,Horror,Sci-Fi,NaN,NaN,NaN,NaN,Apr,2015
3,Stranger in the House (2015),Horror| Mystery| Thriller,Spain,4.6,"Warwick, New York, USA",Horror,Mystery,Thriller,NaN,NaN,NaN,NaN,NaN,May,2017
4,Rise of the Animals (2011),Adventure| Comedy| Horror,USA,3.6,"Rochester, New York, USA",Adventure,Comedy,Horror,NaN,NaN,NaN,NaN,NaN,May,2012

In [38]:
#
for years in IMDB_Clean4_df['Release Year']:
    IMDB_Clean_2012 = IMDB_Clean4_df.loc[IMDB_Clean4_df['Release Year'] == 2012]
    review_rating_2012 = IMDB_Clean_2012['Review Rating'] 
    print(IMDB_Clean_2012.head())
    print(print(st.normaltest(temperatures.sample(3529))))

                                 Title                      Genres
0                           Gut (2012)     Drama| Horror| Thriller  \
4           Rise of the Animals (2011)   Adventure| Comedy| Horror
11                    I Am ZoZo (2012)            Horror| Thriller
15            2: Voodoo Academy (2012)                      Horror
16  Return of the Killer Shrews (2012)                      Horror

   Release Country  Review Rating
0              USA            3.9  \
4              USA            3.6
11             USA            3.6
15             USA            4.5
16             USA            2.7

                                    Filming Locations     Genre_1    Genre_2
0                                       New York, USA       Drama     Horror  \
4                            Rochester, New York, USA   Adventure     Comedy
11  San Juan Island, San Juan Islands, Washington,...      Horror   Thriller
15                            Malibu, California, USA      Horror        NaN
16  Sanna Movie Ranch - Soledad Canyon Road, Agua ...      Horror        NaN

      Genre_3 Genre_4 Genre_5 Genre_6 Genre_7 Genre_8 Month  Release Year
0    Thriller     NaN     NaN     NaN     NaN     NaN   Oct          2012
4      Horror     NaN     NaN     NaN     NaN     NaN   May          2012
11        NaN     NaN     NaN     NaN     NaN     NaN   Feb          2012
15        NaN     NaN     NaN     NaN     NaN     NaN   Oct          2012
16        NaN     NaN     NaN     NaN     NaN     NaN  None          2012
251

4.6310756972111555