In [1]:
#Import all needed Packages

import matplotlib.pyplot as plt

import pandas as pd

import numpy as np

In [2]:
#Set path to .csv file
IMDB_df = pd.read_csv('IMDB_Horror_Movies.csv')
IMDB_df.head()

,Title,Genres,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Plot,Cast,Language,Filming Locations,Budget
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,NaN,3.9,91 min,"Directed by Elias. With Jason Vail, Nicholas W...",Jason Vail|Nicholas Wilder|Sarah Schoofs|Kirst...,English,"New York, USA",NaN
1,The Haunting of Mia Moss (2017),Horror,13-Jan-17,USA,NaN,NaN,NaN,"Directed by Jake Zelch. With Nicola Fiore, Bri...",Nicola Fiore|Brinke Stevens|Curtis Carnahan|Ja...,English,NaN,"$30,000"
2,Sleepwalking (2017),Horror,21-Oct-17,Canada,NaN,NaN,NaN,"Directed by David Briggs. With Alysia Topol, A...",Alysia Topol|Anthony Makela|Kelsi Ashley|Patri...,English,"Sudbury, Ontario, Canada",NaN
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,NOT RATED,3.7,82 min,"Directed by M. Kelley, Shawn C. Phillips, Alex...",Veronica Ricci|Nicholas Adam Clark|James Culle...,English,"Baltimore, Maryland, USA",NaN
4,Infidus (2015),Crime| Drama| Horror,10-Apr-15,USA,NaN,5.8,80 min,"Directed by Giulio De Santi. With Bonini Mino,...",Bonini Mino|Massimo Caratelli|Maurizio Zaffino...,Italian,NaN,NaN

In [3]:
#Clean .csv file
IMDB_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328 entries, 0 to 3327
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              3328 non-null   object
 1   Genres             3327 non-null   object
 2   Release Date       3328 non-null   object
 3   Release Country    3328 non-null   object
 4   Movie Rating       1451 non-null   object
 5   Review Rating      3076 non-null   float64
 6   Movie Run Time     2784 non-null   object
 7   Plot               3327 non-null   object
 8   Cast               3314 non-null   object
 9   Language           3256 non-null   object
 10  Filming Locations  2096 non-null   object
 11  Budget             1234 non-null   object
dtypes: float64(1), object(11)
memory usage: 312.1+ KB

In [4]:
IMDB_df.describe()

       Review Rating
count    3076.000000
mean        5.077016
std         1.474272
min         1.000000
25%         4.000000
50%         5.000000
75%         6.100000
max         9.800000

In [5]:
IMDB_Clean1_df = IMDB_df[["Title", "Genres", "Release Date","Release Country" ,"Review Rating", "Filming Locations"]]
IMDB_Clean1_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA"
1,The Haunting of Mia Moss (2017),Horror,13-Jan-17,USA,NaN,NaN
2,Sleepwalking (2017),Horror,21-Oct-17,Canada,NaN,"Sudbury, Ontario, Canada"
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA"
4,Infidus (2015),Crime| Drama| Horror,10-Apr-15,USA,5.8,NaN

In [6]:
IMDB_Clean1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328 entries, 0 to 3327
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              3328 non-null   object
 1   Genres             3327 non-null   object
 2   Release Date       3328 non-null   object
 3   Release Country    3328 non-null   object
 4   Review Rating      3076 non-null   float64
 5   Filming Locations  2096 non-null   object
dtypes: float64(1), object(5)
memory usage: 156.1+ KB

In [7]:
IMDB_Clean2_df = IMDB_Clean1_df.dropna()
IMDB_Clean2_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 3327
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              1960 non-null   object
 1   Genres             1960 non-null   object
 2   Release Date       1960 non-null   object
 3   Release Country    1960 non-null   object
 4   Review Rating      1960 non-null   float64
 5   Filming Locations  1960 non-null   object
dtypes: float64(1), object(5)
memory usage: 107.2+ KB

In [8]:
IMDB_Clean2_df.Genres.value_counts()

Genres
 Horror                                                 482
 Horror| Thriller                                       304
 Comedy| Horror                                         143
 Horror| Mystery| Thriller                              131
 Drama| Horror| Thriller                                104
                                                       ...
 Drama| Horror| Musical| Thriller                         1
 Action| Crime| Horror| Western                           1
 Action| Adult| Comedy| Horror| Sci-Fi| Western           1
 Comedy| Horror| Romance| Thriller                        1
 Comedy| Fantasy| Horror| Mystery| Romance| Thriller      1
Name: count, Length: 196, dtype: int64

In [9]:
var = [len(x.split('|'))for x in IMDB_Clean2_df['Genres'].tolist()]
var.sort()
var[-10:]

[6, 6, 6, 6, 7, 7, 7, 7, 7, 8]

In [10]:
IMDB_Clean2_df["Release Date"].head(25)

0     26-Oct-12
3     23-Apr-13
7     25-Apr-15
8     28-May-17
11     1-May-12
13         2013
14    21-Mar-17
15    13-Jan-17
16    23-Mar-15
17     8-Apr-16
19    16-Sep-14
20    18-Feb-12
21     8-Jun-13
22     5-May-15
24    25-May-16
25     1-Oct-12
26         2012
28    15-Aug-14
29         2013
30    19-Apr-13
31     2-Nov-16
36     9-Mar-17
38    21-Feb-14
39    27-Sep-14
40    31-Mar-14
Name: Release Date, dtype: object

In [12]:
for x in range(1,9):
    IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
IMDB_Clean2_df.head()

C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]
C:\Users\perry\AppData\Local\Temp\ipykernel_25584\3989293530.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IMDB_Clean2_df[f'Genre_{x}'] = [np.nan for y in range(len(IMDB_Clean2_df))]

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
IMDB_Clean3_df= IMDB_Clean2_df.reset_index(drop=True)
IMDB_Clean3_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
for x,y in enumerate(IMDB_Clean3_df['Genres'].tolist()):
    try:
        temp_var = y.split('|').replace(' ','')
        if len(temp_var) == 1:
            continue
        else:
            temp_var.remove(temp_var.index('Horror'))
            
        for i,j in enumerate(temp_var):

            IMDB_Clean3_df.at[x,f"Genre_{i+1}"]=j
    except:
        continue

In [100]:
IMDB_Clean3_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Month,Release Year,Genre_1,Genre_2,Genre_3,Genre_4,Genre_5,Genre_6,Genre_7,Genre_8
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Oct,2012.0,Drama,Horror,Thriller,NaN,NaN,NaN,NaN,NaN
1,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Apr,2013.0,Comedy,Horror,Thriller,Sci-Fi,NaN,NaN,NaN,NaN
2,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Apr,2015.0,Action,Drama,Horror,Sci-Fi,NaN,NaN,NaN,NaN
3,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",May,2017.0,Horror,Mystery,Thriller,Sci-Fi,NaN,NaN,NaN,NaN
4,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",May,2012.0,Adventure,Comedy,Horror,NaN,NaN,NaN,NaN,NaN

In [47]:
IMDB_Clean4_df = IMDB_Clean3_df[['Day', 'Month', 'Year']] =  IMDB_Clean3_df.str.split("-", expand = True)
print(IMDB_Clean4_df.count())
IMDB_Clean4_df.head()

Title                1960
Genres               1960
Release Date         1960
Release Country      1960
Review Rating        1960
Filming Locations    1960
Day                  1960
Month                1865
Year                 1865
Release Year         1960
dtype: int64

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Day,Month,Year,Release Year
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",26,Oct,12,2012
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",23,Apr,13,2013
7,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",25,Apr,15,2015
8,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",28,May,17,2017
11,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",1,May,12,2012

In [39]:
IMDB_Clean4_df['Release Year'] = pd.DatetimeIndex(IMDB_Clean4_df['Release Date']).year
IMDB_Clean4_df.head()

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Day,Month,Year,Release Year
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",26,Oct,12,2012
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",23,Apr,13,2013
7,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",25,Apr,15,2015
8,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",28,May,17,2017
11,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",1,May,12,2012

In [40]:
IMDB_Clean4_df.count()

Title                1960
Genres               1960
Release Date         1960
Release Country      1960
Review Rating        1960
Filming Locations    1960
Day                  1960
Month                1865
Year                 1865
Release Year         1960
dtype: int64

In [53]:
IMDB_Clean4_df.head(30)

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Month,Release Year
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Oct,2012
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Apr,2013
7,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Apr,2015
8,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",May,2017
11,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",May,2012
14,Sexy Durga (2017),Drama| Fantasy| Horror| Mystery| Thriller,21-Mar-17,USA,5.9,"Thiruvananthapuram, Kerala, India",Mar,2017
15,Circus of the Dead (2014),Action| Horror| Thriller,13-Jan-17,USA,6.0,"Odessa, Texas, USA",Jan,2017
16,Zombie Resurrection (2014),Horror,23-Mar-15,UK,2.7,"Hampshire, England, UK",Mar,2015
17,Falling (2016),Drama| Horror| Romance| Thriller,8-Apr-16,USA,7.1,"Utica, New York, USA",Apr,2016
19,Devil's Tower (2014),Horror,16-Sep-14,UK,3.4,"Derbyshire, England, UK",Sep,2014
20,I Am ZoZo (2012),Horror| Thriller,18-Feb-12,USA,3.6,"San Juan Island, San Juan Islands, Washington,...",Feb,2012
21,Before Dawn (2013),Horror,8-Jun-13,Japan,4.7,"Yorkshire, England, UK",Jun,2013
22,Apparition (2015),Fantasy| Horror| Thriller,5-May-15,USA,4.0,"Philadelphia, Pennsylvania, USA",May,2015
24,Don't Look in the Basement 2 (2015),Horror| Thriller,25-May-16,USA,4.0,"Tehuacana, Texas, USA",May,2016
25,2: Voodoo Academy (2012),Horror,1-Oct-12,USA,4.5,"Malibu, California, USA",Oct,2012
28,Septic Man (2013),Horror,15-Aug-14,USA,4.1,"Collingwood, Ontario, Canada",Aug,2014
30,Her Cry: La Llorona Investigation (2013),Horror,19-Apr-13,USA,5.4,"Houston, Texas, USA",Apr,2013
31,The Canadoo (2016),Horror,2-Nov-16,USA,4.0,"Atlanta, Georgia, USA",Nov,2016
36,Ular Tangga (2017),Horror| Thriller,9-Mar-17,Indonesia,7.1,"Gunung Pancar, Indonesia",Mar,2017
38,Haunted House on Sorority Row (2014),Horror,21-Feb-14,USA,5.6,"Dayton, Ohio, USA",Feb,2014
39,Victimized (2014),Drama| Horror| Thriller,27-Sep-14,USA,6.9,"Sarasota, Florida, USA",Sep,2014
40,The Unwanted (2014),Drama| Horror| Mystery| Romance,31-Mar-14,USA,4.0,"Atlanta, Georgia, USA",Mar,2014
41,Hotel Inferno (2013),Action| Horror,16-Dec-13,USA,4.7,Tunisia,Dec,2013
44,Play Motel (1979),Crime| Horror| Romance| Thriller,25-Aug-15,USA,5.3,"Cine International, Rome, Lazio, Italy",Aug,2015
45,Turned (2015),Drama| Horror,4-Sep-15,USA,7.3,"Staten Island, New York, USA",Sep,2015
51,The Ouija Exorcism (2015),Horror,6-Oct-15,USA,2.1,"Los Angeles, California, USA",Oct,2015
52,Soldiers of the Damned (2015),Action| Horror| Thriller| War,8-Aug-15,UK,3.6,"Cumbria, England, UK",Aug,2015
53,Smothered (2016),Comedy| Horror,29-Mar-16,USA,4.1,"Baton Rouge, Louisiana, USA",Mar,2016
58,Scars (2016),Horror,23-Jan-17,UK,3.9,"Toronto, Ontario, Canada",Jan,2017
59,Legend Has It (2009),Horror,17-Sep-14,UK,4.1,"Pasadena, California, USA",Sep,2014

In [54]:

IMDB_Clean5_df = IMDB_Clean4_df.dropna()

IMDB_Clean5_df.head(30)

,Title,Genres,Release Date,Release Country,Review Rating,Filming Locations,Month,Release Year
0,Gut (2012),Drama| Horror| Thriller,26-Oct-12,USA,3.9,"New York, USA",Oct,2012
3,Treasure Chest of Horrors II (2013),Comedy| Horror| Thriller,23-Apr-13,USA,3.7,"Baltimore, Maryland, USA",Apr,2013
7,Parasyte: Part 2 (2015),Action| Drama| Horror| Sci-Fi,25-Apr-15,Japan,6.5,"Tokyo, Japan",Apr,2015
8,Stranger in the House (2015),Horror| Mystery| Thriller,28-May-17,Spain,4.6,"Warwick, New York, USA",May,2017
11,Rise of the Animals (2011),Adventure| Comedy| Horror,1-May-12,USA,3.6,"Rochester, New York, USA",May,2012
14,Sexy Durga (2017),Drama| Fantasy| Horror| Mystery| Thriller,21-Mar-17,USA,5.9,"Thiruvananthapuram, Kerala, India",Mar,2017
15,Circus of the Dead (2014),Action| Horror| Thriller,13-Jan-17,USA,6.0,"Odessa, Texas, USA",Jan,2017
16,Zombie Resurrection (2014),Horror,23-Mar-15,UK,2.7,"Hampshire, England, UK",Mar,2015
17,Falling (2016),Drama| Horror| Romance| Thriller,8-Apr-16,USA,7.1,"Utica, New York, USA",Apr,2016
19,Devil's Tower (2014),Horror,16-Sep-14,UK,3.4,"Derbyshire, England, UK",Sep,2014
20,I Am ZoZo (2012),Horror| Thriller,18-Feb-12,USA,3.6,"San Juan Island, San Juan Islands, Washington,...",Feb,2012
21,Before Dawn (2013),Horror,8-Jun-13,Japan,4.7,"Yorkshire, England, UK",Jun,2013
22,Apparition (2015),Fantasy| Horror| Thriller,5-May-15,USA,4.0,"Philadelphia, Pennsylvania, USA",May,2015
24,Don't Look in the Basement 2 (2015),Horror| Thriller,25-May-16,USA,4.0,"Tehuacana, Texas, USA",May,2016
25,2: Voodoo Academy (2012),Horror,1-Oct-12,USA,4.5,"Malibu, California, USA",Oct,2012
28,Septic Man (2013),Horror,15-Aug-14,USA,4.1,"Collingwood, Ontario, Canada",Aug,2014
30,Her Cry: La Llorona Investigation (2013),Horror,19-Apr-13,USA,5.4,"Houston, Texas, USA",Apr,2013
31,The Canadoo (2016),Horror,2-Nov-16,USA,4.0,"Atlanta, Georgia, USA",Nov,2016
36,Ular Tangga (2017),Horror| Thriller,9-Mar-17,Indonesia,7.1,"Gunung Pancar, Indonesia",Mar,2017
38,Haunted House on Sorority Row (2014),Horror,21-Feb-14,USA,5.6,"Dayton, Ohio, USA",Feb,2014
39,Victimized (2014),Drama| Horror| Thriller,27-Sep-14,USA,6.9,"Sarasota, Florida, USA",Sep,2014
40,The Unwanted (2014),Drama| Horror| Mystery| Romance,31-Mar-14,USA,4.0,"Atlanta, Georgia, USA",Mar,2014
41,Hotel Inferno (2013),Action| Horror,16-Dec-13,USA,4.7,Tunisia,Dec,2013
44,Play Motel (1979),Crime| Horror| Romance| Thriller,25-Aug-15,USA,5.3,"Cine International, Rome, Lazio, Italy",Aug,2015
45,Turned (2015),Drama| Horror,4-Sep-15,USA,7.3,"Staten Island, New York, USA",Sep,2015
51,The Ouija Exorcism (2015),Horror,6-Oct-15,USA,2.1,"Los Angeles, California, USA",Oct,2015
52,Soldiers of the Damned (2015),Action| Horror| Thriller| War,8-Aug-15,UK,3.6,"Cumbria, England, UK",Aug,2015
53,Smothered (2016),Comedy| Horror,29-Mar-16,USA,4.1,"Baton Rouge, Louisiana, USA",Mar,2016
58,Scars (2016),Horror,23-Jan-17,UK,3.9,"Toronto, Ontario, Canada",Jan,2017
59,Legend Has It (2009),Horror,17-Sep-14,UK,4.1,"Pasadena, California, USA",Sep,2014